require("dotenv").config();
const express=require("express");
const cors=require("cors");
const connectDB=require("./config/db");
const authRoutes=require("./routes/authRoutes");
const aiRoutes=require("./routes/aiRoutes");
const app=express();
app.use(cors());
app.use(express.json());
connectDB();
app.use("/api/auth",authRoutes);
app.use("/api/ai",aiRoutes);
app.use("/api/admin", require("./routes/adminRoutes"));
app.listen(5000,()=>console.log("🔥 Backend 5000 portunda çalışıyor"));
